/*----- PROTECTED REGION ID(LiberaEventReceiverStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        LiberaEventReceiverStateMachine.cpp
//
// description : State machine file for the LiberaEventReceiver class
//
// project :     Libera BPM Event Receiver Device Server
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <LiberaEventReceiver.h>

/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::LiberaEventReceiverStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  UNKNOWN  |  Device is not [or not properly] initialized
//  FAULT    |  Device initialization failed or unrecoverable error
//  ON       |  BPM is up and running


namespace LiberaEventReceiver_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_PMNotificationCounter_allowed()
 *	Description : Execution allowed for PMNotificationCounter attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_PMNotificationCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PMNotificationCounter attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::PMNotificationCounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::PMNotificationCounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_OffsetTune_allowed()
 *	Description : Execution allowed for OffsetTune attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_OffsetTune_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for OffsetTune attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::OffsetTuneStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::OffsetTuneStateAllowed_WRITE

	//	Not any excluded states for OffsetTune attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::OffsetTuneStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::OffsetTuneStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_CompensateTune_allowed()
 *	Description : Execution allowed for CompensateTune attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_CompensateTune_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for CompensateTune attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::CompensateTuneStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::CompensateTuneStateAllowed_WRITE

	//	Not any excluded states for CompensateTune attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::CompensateTuneStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::CompensateTuneStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_MCPLLStatus_allowed()
 *	Description : Execution allowed for MCPLLStatus attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_MCPLLStatus_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for MCPLLStatus attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::MCPLLStatusStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::MCPLLStatusStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_Temp3_allowed()
 *	Description : Execution allowed for Temp3 attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_Temp3_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Temp3 attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::Temp3StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::Temp3StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T0Delay_allowed()
 *	Description : Execution allowed for T0Delay attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T0Delay_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T0Delay attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0DelayStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0DelayStateAllowed_WRITE

	//	Not any excluded states for T0Delay attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0DelayStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0DelayStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_RtcDecoderSwitch_allowed()
 *	Description : Execution allowed for RtcDecoderSwitch attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_RtcDecoderSwitch_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for RtcDecoderSwitch attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::RtcDecoderSwitchStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::RtcDecoderSwitchStateAllowed_WRITE

	//	Not any excluded states for RtcDecoderSwitch attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::RtcDecoderSwitchStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::RtcDecoderSwitchStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_McSource_allowed()
 *	Description : Execution allowed for McSource attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_McSource_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for McSource attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::McSourceStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::McSourceStateAllowed_WRITE

	//	Not any excluded states for McSource attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::McSourceStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::McSourceStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T0Direction_allowed()
 *	Description : Execution allowed for T0Direction attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T0Direction_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T0Direction attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0DirectionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0DirectionStateAllowed_WRITE

	//	Not any excluded states for T0Direction attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0DirectionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0DirectionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T0OutputType_allowed()
 *	Description : Execution allowed for T0OutputType attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T0OutputType_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T0OutputType attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0OutputTypeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0OutputTypeStateAllowed_WRITE

	//	Not any excluded states for T0OutputType attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0OutputTypeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0OutputTypeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T0State_allowed()
 *	Description : Execution allowed for T0State attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T0State_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T0State attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0StateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0StateStateAllowed_WRITE

	//	Not any excluded states for T0State attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0StateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0StateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1Source_allowed()
 *	Description : Execution allowed for T1Source attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1Source_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1Source attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1SourceStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1SourceStateAllowed_WRITE

	//	Not any excluded states for T1Source attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1SourceStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1SourceStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2Source_allowed()
 *	Description : Execution allowed for T2Source attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2Source_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2Source attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2SourceStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2SourceStateAllowed_WRITE

	//	Not any excluded states for T2Source attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2SourceStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2SourceStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_MgtOut_allowed()
 *	Description : Execution allowed for MgtOut attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_MgtOut_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for MgtOut attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::MgtOutStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::MgtOutStateAllowed_WRITE

	//	Not any excluded states for MgtOut attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::MgtOutStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::MgtOutStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T0inMask_allowed()
 *	Description : Execution allowed for T0inMask attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T0inMask_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T0inMask attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0inMaskStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0inMaskStateAllowed_WRITE

	//	Not any excluded states for T0inMask attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0inMaskStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0inMaskStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1inMask_allowed()
 *	Description : Execution allowed for T1inMask attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1inMask_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1inMask attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1inMaskStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1inMaskStateAllowed_WRITE

	//	Not any excluded states for T1inMask attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1inMaskStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1inMaskStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2inMask_allowed()
 *	Description : Execution allowed for T2inMask attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2inMask_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2inMask attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2inMaskStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2inMaskStateAllowed_WRITE

	//	Not any excluded states for T2inMask attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2inMaskStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2inMaskStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T0idOutput_allowed()
 *	Description : Execution allowed for T0idOutput attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T0idOutput_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T0idOutput attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0idOutputStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0idOutputStateAllowed_WRITE

	//	Not any excluded states for T0idOutput attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0idOutputStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0idOutputStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1inFunction_allowed()
 *	Description : Execution allowed for T1inFunction attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1inFunction_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1inFunction attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1inFunctionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1inFunctionStateAllowed_WRITE

	//	Not any excluded states for T1inFunction attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1inFunctionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1inFunctionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2inFunction_allowed()
 *	Description : Execution allowed for T2inFunction attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2inFunction_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2inFunction attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2inFunctionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2inFunctionStateAllowed_WRITE

	//	Not any excluded states for T2inFunction attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2inFunctionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2inFunctionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_MCinMask_allowed()
 *	Description : Execution allowed for MCinMask attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_MCinMask_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for MCinMask attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::MCinMaskStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::MCinMaskStateAllowed_WRITE

	//	Not any excluded states for MCinMask attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::MCinMaskStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::MCinMaskStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_MCinFunction_allowed()
 *	Description : Execution allowed for MCinFunction attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_MCinFunction_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for MCinFunction attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::MCinFunctionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::MCinFunctionStateAllowed_WRITE

	//	Not any excluded states for MCinFunction attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::MCinFunctionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::MCinFunctionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T0Duration_allowed()
 *	Description : Execution allowed for T0Duration attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T0Duration_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T0Duration attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0DurationStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0DurationStateAllowed_WRITE

	//	Not any excluded states for T0Duration attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0DurationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0DurationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_InterlockID_allowed()
 *	Description : Execution allowed for InterlockID attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_InterlockID_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for InterlockID attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::InterlockIDStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::InterlockIDStateAllowed_WRITE

	//	Not any excluded states for InterlockID attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::InterlockIDStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::InterlockIDStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2EdgeFalling_allowed()
 *	Description : Execution allowed for T2EdgeFalling attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2EdgeFalling_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2EdgeFalling attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2EdgeFallingStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2EdgeFallingStateAllowed_WRITE

	//	Not any excluded states for T2EdgeFalling attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2EdgeFallingStateAllowed_READ) ENABLED START -----*/
		
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2EdgeFallingStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2EdgeRising_allowed()
 *	Description : Execution allowed for T2EdgeRising attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2EdgeRising_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2EdgeRising attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2EdgeRisingStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2EdgeRisingStateAllowed_WRITE

	//	Not any excluded states for T2EdgeRising attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2EdgeRisingStateAllowed_READ) ENABLED START -----*/
		
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2EdgeRisingStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1EdgeFalling_allowed()
 *	Description : Execution allowed for T1EdgeFalling attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1EdgeFalling_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1EdgeFalling attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1EdgeFallingStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1EdgeFallingStateAllowed_WRITE

	//	Not any excluded states for T1EdgeFalling attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1EdgeFallingStateAllowed_READ) ENABLED START -----*/
		
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1EdgeFallingStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1EdgeRising_allowed()
 *	Description : Execution allowed for T1EdgeRising attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1EdgeRising_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1EdgeRising attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1EdgeRisingStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1EdgeRisingStateAllowed_WRITE

	//	Not any excluded states for T1EdgeRising attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1EdgeRisingStateAllowed_READ) ENABLED START -----*/
		
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1EdgeRisingStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2IdInput_allowed()
 *	Description : Execution allowed for T2IdInput attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2IdInput_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2IdInput attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2IdInputStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2IdInputStateAllowed_WRITE

	//	Not any excluded states for T2IdInput attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2IdInputStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2IdInputStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1IdInput_allowed()
 *	Description : Execution allowed for T1IdInput attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1IdInput_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1IdInput attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1IdInputStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1IdInputStateAllowed_WRITE

	//	Not any excluded states for T1IdInput attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1IdInputStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1IdInputStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1Direction_allowed()
 *	Description : Execution allowed for T1Direction attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1Direction_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1Direction attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1DirectionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1DirectionStateAllowed_WRITE

	//	Not any excluded states for T1Direction attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1DirectionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1DirectionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2Direction_allowed()
 *	Description : Execution allowed for T2Direction attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2Direction_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2Direction attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2DirectionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2DirectionStateAllowed_WRITE

	//	Not any excluded states for T2Direction attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2DirectionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2DirectionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_SynchronizeLMT_allowed()
 *	Description : Execution allowed for SynchronizeLMT attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_SynchronizeLMT_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for SynchronizeLMT attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::SynchronizeLMTStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::SynchronizeLMTStateAllowed_WRITE

	//	Not any excluded states for SynchronizeLMT attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::SynchronizeLMTStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::SynchronizeLMTStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_RTCTimestamp_allowed()
 *	Description : Execution allowed for RTCTimestamp attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_RTCTimestamp_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for RTCTimestamp attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::RTCTimestampStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::RTCTimestampStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_RTCTimestampState_allowed()
 *	Description : Execution allowed for RTCTimestampState attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_RTCTimestampState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for RTCTimestampState attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::RTCTimestampStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::RTCTimestampStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1State_allowed()
 *	Description : Execution allowed for T1State attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1State_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1State attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1StateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1StateStateAllowed_WRITE

	//	Not any excluded states for T1State attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1StateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1StateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2State_allowed()
 *	Description : Execution allowed for T2State attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2State_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2State attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2StateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2StateStateAllowed_WRITE

	//	Not any excluded states for T2State attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2StateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2StateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1Duration_allowed()
 *	Description : Execution allowed for T1Duration attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1Duration_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1Duration attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1DurationStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1DurationStateAllowed_WRITE

	//	Not any excluded states for T1Duration attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1DurationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1DurationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T1idOutput_allowed()
 *	Description : Execution allowed for T1idOutput attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T1idOutput_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T1idOutput attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1idOutputStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1idOutputStateAllowed_WRITE

	//	Not any excluded states for T1idOutput attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T1idOutputStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T1idOutputStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2idOutput_allowed()
 *	Description : Execution allowed for T2idOutput attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2idOutput_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2idOutput attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2idOutputStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2idOutputStateAllowed_WRITE

	//	Not any excluded states for T2idOutput attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2idOutputStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2idOutputStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T0IdInput_allowed()
 *	Description : Execution allowed for T0IdInput attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T0IdInput_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T0IdInput attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0IdInputStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0IdInputStateAllowed_WRITE

	//	Not any excluded states for T0IdInput attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T0IdInputStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T0IdInputStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_T2Duration_allowed()
 *	Description : Execution allowed for T2Duration attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_T2Duration_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for T2Duration attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2DurationStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2DurationStateAllowed_WRITE

	//	Not any excluded states for T2Duration attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::T2DurationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::T2DurationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_RtcT1inMask_allowed()
 *	Description : Execution allowed for RtcT1inMask attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_RtcT1inMask_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for RtcT1inMask attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::RtcT1inMaskStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::RtcT1inMaskStateAllowed_WRITE

	//	Not any excluded states for RtcT1inMask attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::RtcT1inMaskStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::RtcT1inMaskStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_RtcT2inMask_allowed()
 *	Description : Execution allowed for RtcT2inMask attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_RtcT2inMask_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for RtcT2inMask attribute in Write access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::RtcT2inMaskStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::RtcT2inMaskStateAllowed_WRITE

	//	Not any excluded states for RtcT2inMask attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::RtcT2inMaskStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::RtcT2inMaskStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_DDTriggerCounter_allowed()
 *	Description : Execution allowed for DDTriggerCounter attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_DDTriggerCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DDTriggerCounter attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::DDTriggerCounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::DDTriggerCounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_UserData_allowed()
 *	Description : Execution allowed for UserData attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_UserData_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for UserData attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::UserDataStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::UserDataStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_logs_allowed()
 *	Description : Execution allowed for logs attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_logs_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for logs attribute in read access.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::logsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::logsStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_GetParameters_allowed()
 *	Description : Execution allowed for GetParameters attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_GetParameters_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::UNKNOWN ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(LiberaEventReceiver::GetParametersStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::GetParametersStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_ReloadSystemProperties_allowed()
 *	Description : Execution allowed for ReloadSystemProperties attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_ReloadSystemProperties_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::UNKNOWN ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(LiberaEventReceiver::ReloadSystemPropertiesStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::ReloadSystemPropertiesStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_MagicCommand_allowed()
 *	Description : Execution allowed for MagicCommand attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_MagicCommand_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for MagicCommand command.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::MagicCommandStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::MagicCommandStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_AnnounceSynchronization_allowed()
 *	Description : Execution allowed for AnnounceSynchronization attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_AnnounceSynchronization_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for AnnounceSynchronization command.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::AnnounceSynchronizationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::AnnounceSynchronizationStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_ForceInitSettings_allowed()
 *	Description : Execution allowed for ForceInitSettings attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_ForceInitSettings_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::UNKNOWN ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(LiberaEventReceiver::ForceInitSettingsStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::ForceInitSettingsStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_SetTraceLevel_allowed()
 *	Description : Execution allowed for SetTraceLevel attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_SetTraceLevel_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::UNKNOWN ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(LiberaEventReceiver::SetTraceLevelStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::SetTraceLevelStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LiberaEventReceiver::is_StartSynchronization_allowed()
 *	Description : Execution allowed for StartSynchronization attribute
 */
//--------------------------------------------------------
bool LiberaEventReceiver::is_StartSynchronization_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StartSynchronization command.
	/*----- PROTECTED REGION ID(LiberaEventReceiver::StartSynchronizationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LiberaEventReceiver::StartSynchronizationStateAllowed
	return true;
}

}	//	End of namespace
